sources:
  - name: Wiki
    handler:
      openapi:
        source: https://api.apis.guru/v2/specs/wikimedia.org/1.0.0/swagger.yaml

additionalTypeDefs: |
      extend type Query {
        viewsInPastMonth(project: String!): Float!
        viewsOver500K(project: String!): PageviewTops
        viewsTop(project: String!): PageviewTops
      }
      extend type PageviewTops {
        topViewArticleName: String
      }
additionalResolvers:
  - ./src/mesh/additional-resolvers.js
